version: '3'

services:
  myredis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  app:
    build:
      context: flask/
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"
    depends_on:
      - myredis
  queue:
    build:
      context: queue/
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5050:5050"
    depends_on:
      - app

